### PR TITLE
Upgrade Ganache to 7.5.0

### PR DESCRIPTION
**Pull request by jeffsmale90**
Upgrades to [Ganache 7.5.0](https://github.com/trufflesuite/ganache/releases/tag/v7.5.0), including the Better, Stronger, Faster performance improvements introduced in [Ganache 7.3.1](https://github.com/trufflesuite/ganache/releases/tag/v7.3.1)

### CODE REVIEW

**Comment by mds1** [comment]
Thanks! I just want to update the README benchmarks before merging, hopefully can do that this weekend

**Comment by jeffsmale90** [comment]
@mds1 any way I can help with this?

**Comment by mds1** [comment]
Oops sorry, accidentally archived all github emails the other week so lost track of this! Thanks for the reminder 🙂

**Comment by jeffsmale90** [comment]
> Oops sorry, accidentally archived all github emails the other week so lost track of this! Thanks for the reminder 🙂

Ha! No worries. Good to have zero inbox :)

**Comment by mds1** [comment]
Updated other packages and re-ran the ganache, hardhat, foundry benchmarks—thanks @jeffsmale90!

**Pull request merged**
